# docker/docker-compose.spark.yml
services:
  spark-master:
    image: apache/spark:4.1.0-preview3-python3
    container_name: spark-master
    environment:
      - SPARK_MODE=master
    ports:
      - "7077:7077"
      - "8088:8088"
    networks:
      - mlops

  spark-worker-1:
    image: apache/spark:4.1.0-preview3-python3
    container_name: spark-worker-1
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark-master:7077
    depends_on:
      - spark-master
    networks:
      - mlops

networks:
  mlops:
    driver: bridge